modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/ThexXTURBOXx/balkons-weaponmod/issues"
logoFile = "bwm_logo.png"

[[mods]]
modId = "weaponmod"
version = "${file.jarVersion}"
updateJSONURL = "https://raw.githubusercontent.com/ThexXTURBOXx/UpdateJSONs/master/weaponmod.json"
displayName = "Balkon's WeaponMod"
displayURL = "https://www.minecraftforum.net/topic/211517-bwm"
credits = "BalkondeurAlpha, HyperSpeeed"
authors = "BalkondeurAlpha, HyperSpeeed"
description = '''
Throw a spear in a zombie's head!
Cut a skeleton in half with your brand new halberd!
Shoot some slimes in pieces with an old musket!
And more!
'''

[[dependencies.weaponmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
side = "BOTH"
