modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/ThexXTURBOXx/balkons-weaponmod/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
license = "${mod_license}"
updateJSONURL = "https://raw.githubusercontent.com/ThexXTURBOXx/UpdateJSONs/master/weaponmod.json"
displayName = "${mod_name}"
displayURL = "https://www.minecraftforum.net/topic/211517-bwm"
logoFile = "bwm_logo.png"
credits = "${mod_authors}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
