name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to CurseForge and Modrinth
        uses: Kir-Antipov/mc-publish@v3
        with:
          modrinth-id: MCF15nCy
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1033985
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: |
            build/libs/!(*-@(dev|dev-shadow|sources|javadoc)).jar
            build/libs/*-@(dev|dev-shadow|sources|javadoc).jar
          name: Sodium 0.3.2 for Minecraft 1.17.1
          version: mc1.17.1-0.3.2
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: forge
          game-versions: 1.12.2
          java: 8
